### ISSUE TITLE
NODAL is not supported on v0.6.2

### ISSUE THREAD

**Issue by Omazaria** [phrb/StochasticSearch.jl#30]
I am using Julia 0.6.2 and when trying to add NODAL I get the following error.

> ERROR: NODAL can't be installed because it has no versions that support 0.6.2 of julia. You may need
 to update METADATA by running `Pkg.update()`

**Comment by phrb** [comment]
Hi, thanks for submitting an issue!

You can install the `StochasticSearch` package in Julia 0.6.2, which is NODAL's old name. Since the name change the older versions are only reachable by `StochasticSearch`.

The Julia 0.6.2 version is outdated, but I can help you use it if you need to!

I am sorry, but I am only supporting Julia nightly (0.7) from now on. Any chance you can change to it?

**Comment by Omazaria** [comment]
Hi, thanks for the help.

I will try to use `StochasticSearch` then. I hope they have the features. 

Since the 0.7 is not released yet, it will be difficult to convince my colleagues. I think I will stick with the 0.6.2 and `colleagues`.

**Comment by phrb** [comment]
No problem! What features do you need?

Feel free to comment on this issue or open a new one if you need help.

**Comment by Omazaria** [comment]
The first idea is to use either simulated annealing or tabu search. But first I will try to have a grasp on the different options available. I will let you know if any problem occurs. Thank you.

**Comment by phrb** [comment]
Ok, I will close this issue then.
